# Toplevel Makefile include file for statist.
# 
# It is Free Software distributed under the GNU General Public License v>=2.
# See the file COPYING for details.
###################################

PREFIX=/progetti/statist-1.4.2/os2
DOCDIR=$(PREFIX)/share/doc/statist
MESSAGE_CATALOGS=$(PREFIX)/share/locale
